### PR TITLE
93 bdd fix delete

### PR DESCRIPTION
**Pull request by slydomon**
Create an UI ;
Behave pass: all (get, post , put, delete) list, list with query
Temporary update the get function in ResourceCollection as the find_by function does not work as expected. Need further modification.

### CODE REVIEW

**Comment by o9812** [comment]
Can't not run the behave

**Comment by slydomon** [comment]
How do you run it and what error did you get

**Comment by o9812** [comment]
I run ```vagrant@ubuntu-xenial:/vagrant$ behave```

and I get
```Exception WebDriverException: Message: 'phantomjs' executable needs to be in PATH.

Traceback (most recent call last):
  File "/usr/local/bin/behave", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/behave/__main__.py", line 109, in main
    failed = runner.run()
  File "/usr/local/lib/python2.7/dist-packages/behave/runner.py", line 672, in run
    return self.run_with_paths()
  File "/usr/local/lib/python2.7/dist-packages/behave/runner.py", line 693, in run_with_paths
    return self.run_model()
  File "/usr/local/lib/python2.7/dist-packages/behave/runner.py", line 471, in run_model
    self.run_hook('before_all', context)
  File "/usr/local/lib/python2.7/dist-packages/behave/runner.py", line 405, in run_hook
    self.hooks[name](context, *args)
  File "features/environment.py", line 14, in before_all
    context.driver = webdriver.PhantomJS(executable_path="/usr/local/Cellar/phantomjs/2.1.1/bin/phantomjs")
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/phantomjs/webdriver.py", line 52, in __init__
    self.service.start()
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/common/service.py", line 81, in start
    os.path.basename(self.path), self.start_error_message)
selenium.common.exceptions.WebDriverException: Message: 'phantomjs' executable needs to be in PATH.
```

**Comment by slydomon** [comment]
Did you run “python run.py &” before run behave?

**Comment by o9812** [comment]
I believe  that phantomjs did not correctly installed in the VM, I use `phantomjs -v` to check it and it shows nothing. In contrast, the professor's BDD have already installed phantomjs.

**Comment by o9812** [comment]
Yeah, you are right. It works. Let me merge this one. However, the issue `phantomjs` still be there.

**Pull request merged**
